python3 ./coseg/model/run.py \
    --output_dir=./coseg/saved_models \
    --model_type=roberta \
    --config_name=microsoft/codebert-base \
    --model_name_or_path=microsoft/codebert-base \
    --tokenizer_name=roberta-base \
    --do_eval \
    --do_test \
    --train_data_file=./coseg/dataset/splitted_data/train.jsonl \
    --eval_data_file=./coseg/dataset/splitted_data/valid.jsonl \
    --test_data_file=./coseg/dataset/splitted_data/test.jsonl \
    --epoch 2 \
    --block_size 400 \
    --train_batch_size 16 \
    --eval_batch_size 32 \
    --learning_rate 5e-5 \
    --max_grad_norm 1.0 \
    --evaluate_during_training \
    --seed 123456 2>&1| tee test.log